#!/usr/bin/env bash
#Update package index
sudo apt-get update -y

# Install nginx
apt-get install nginx -y

sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Create a basic HTML file with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Ensure nginx is listening on port 80 by modifying the default configuration
server_block="server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
        try_files \$uri \$uri/ =404;
    }
}"

echo "$server_block" > /etc/nginx/sites-available/default

# Restart nginx server
sudo service nginx restart

# Output success message
echo "Nginx installed and configured successfully."
