#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update -y && sudo apt-get install nginx -y

# Start nginx service
sudo service nginx start

# Create index.html with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Restart Nginx to apply changes
sudo service nginx restart
