#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

#!/usr/bin/env bash
#Install nginx web server
sudo apt-get update -y && sudo apt-get install nginx -y

# Start nginx service
sudo service nginx start

# Change ownership of all files and directories in /var/www to the current user `ubuntu`
sudo chown -R ubuntu /var/www/

# Create index.html with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# redirection must be a “301 Moved Permanently”
ADD301_REDIRECT="\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart

