CREATE USER IF NOT EXISTS holberton_user@localhost IDENTIFIED BY 'projectcorrection280hbtn';
CREATE USER IF NOT EXISTS replica_user@'%' IDENTIFIED BY "#replica_user@012";
CREATE DATABASE IF NOT EXISTS tyrell_corp;
USE tyrell_corp;
CREATE TABLE IF NOT EXISTS nexus6 (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(256) NOT NULL);
INSERT INTO nexus6 (name) VALUES ('Martha');
GRANT REPLICATION CLIENT ON *.* TO 'holberton_user'@'localhost';
GRANT SELECT ON tyrell_corp.nexus6 TO holberton_user@localhost;
GRANT SELECT ON mysql.user TO holberton_user@localhost;
GRANT REPLICATION SLAVE ON *.* TO 'replica_user'@'%';
FLUSH PRIVILEGES;
