#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd

file_path="/etc/passwd"

while IFS= read -r line
do
  user=$(echo "$line" | cut -d ':' -f1)
  gid=$(echo "$line" | cut -d ':' -f4)
  dir=$(echo "$line" | cut -d ':' -f6)
  shell=$(echo "$line" | cut -d ':' -f7)
  uid=$(echo "$line" | cut -d ':' -f3)
  pass=$(echo "$line" | cut -d ':' -f2)
  info=$(echo "$line" | cut -d ':' -f5)

  echo "The user $user is part of the $gid gang, "
  echo "lives in $dir and rides $shell."
  echo "$uid's place is protected by the passcode $pass, "
  echo "more info about the user here: $info"
done < "$file_path"
