#!/bin/env bash

# Update package list and install UFW
sudo apt-get update -y
sudo apt-get install -y ufw

# Enable UFW
sudo ufw enable

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH (port 22)
sudo ufw allow 22/tcp

# Allow HTTPS (port 443)
sudo ufw allow 443/tcp

# Allow HTTP (port 80)
sudo ufw allow 80/tcp

# Reload UFW to apply changes
sudo ufw relaod

# Display UFW status
sudo ufw status verbose
