#!/usr/bin/env bash
# This script updates the Nginx configuration and restarts the Nginx service
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
