#!/usr/bin/env bash
# Bash script that creates an RSA key pair.
# Name of the created private key is  school
# Number of bits in the created key is 4096
# The created key is protected by the passphrase betty

ssh-keygen -f ~/.ssh/school -b 4096 -N betty
echo "RSA key pair created successfully!"
